trigger:
  - master
  - azure-pipeline
  - x64

jobs:
  - job: Windows_release
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://github.com/fdopen/opam-repository-mingw/releases/download/0.0.0.2/OCaml64.exe" -O "build\OCaml64.exe"
        displayName: 'Download OCaml'
      - script: |
          build\OCaml64.exe /S
        displayName: 'Install OCaml'
      - script: |
          C:\Ocaml64\bin\bash -l -c "opam install --yes depext depext-cygwinports; opam depext conf-gmp.1; opam install --yes menhir zarith ocamlgraph ppx_tools cppo num"
          C:\Ocaml64\bin\bash -l -c "wget https://bootstrap.pypa.io/get-pip.py ; python get-pip.py"
        displayName: 'Install dependencies'
      - script: |
          C:\Ocaml64\bin\bash -l -c 'cd $(cygpath "$BUILD_SOURCESDIRECTORY"); echo "##vso[task.setvariable variable=distdir]bincat-win-$(git describe --dirty)"; make windist PYTHON=python'
        displayName: 'Build BinCAT for Windows'
      - task: PublishBuildArtifacts@1
        displayName: Publish BinCAT for Windows installer
        continueOnError: false
        inputs:
          pathtoPublish: $(Build.SourcesDirectory)/$(distdir)
          artifactName: $(distdir)
