name: Build-Windows

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install OCaml
        uses: ocaml/setup-ocaml@v2
        if: runner.os == 'Windows'
        with:
          ocaml-compiler: "ocaml-variants=4.14.1+mingw64"
          allow-prerelease-opam: true
          opam-repositories: |
            opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
            default: https://github.com/ocaml/opam-repository.git

      - name: Install Cygwin dependencies
        run: setup-x86_64.exe -P curl -P git -P make -P python3 -P mingw64-x86_64-gcc-g++ -P mingw64-x86_64-gmp -P zip

      - name: Install Ocaml dependencies
        run: opam depext -i dune menhir ocamlgraph ppxlib zarith

      - name: Make windist
        run: opam exec -- make windist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bincat-installer
          path: bincat-win-*/
